# Generated by Django 6.0.2 on 2026-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_outlet', '0002_alter_books_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
